<?php

/**
 * @file
 * Uses the hbmprivacy service.
 */

/**
 * Implements hook_cron().
 *
 * Uses the Drupal\hbm_privacy\HbmServices\HbmPrivacyService.
 * Retrieve the content of a url.
 */
function hbm_privacy_cron() {
  $hbmPrivacyService = \Drupal::service('hbm_privacy.hbmprivacyservice');
  $statusMessage = $hbmPrivacyService->getPrivacyData();
  \Drupal::logger('hbm_privacy')->notice($statusMessage['lastExecutionTime'] . ' - ' . $statusMessage['status']);
}

/**
 * Implements hook_theme().
 *
 * To add the template definition.
 */
function hbm_privacy_theme() {
  return [
    'hbm_privacy' => [
      'variables' => [
        'hbm_privacy' => NULL,
      ],
    ],
  ];
}
