<?php

/**
 * @file
 * Contains default_content_entity_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function default_content_entity_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the default_content_entity_module module.
    case 'help.page.default_content_entity_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function default_content_entity_module_theme() {
  return [
    'default_content_entity_module' => [
      'render element' => 'children',
    ],
  ];
}
