custommodule.announement:
  type: config_entity
  label: 'Site announcement'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    message:
      type: text
      label: 'Message'


custommodule.message_type.*:
  type: config_entity
  label: 'Message type settings'
  mapping:
    id:
      type: string
      label: 'Machine readable name'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    lancode:
      type: string
      label: 'Default Language'
