<?php

/**
 * @file
 * Contains geoip.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function geoip_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the geoip module.
    case 'help.page.geoip':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Geoip module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function geoip_theme() {
  return [
    'geoip' => [
      'render element' => 'children',
    ],
  ];
}
