<?php

/**
 * @file
 * Custom module that alters forms
 * Implements hook_form_FORM_ID_alter()
 */
function drupalform_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form['site_phone'] = [
    '#type' => 'tel',
    '#title' => t('Site phone'),
    '#default_value' => \Drupal::config('system.site')->get('phonenumber')
  ];

  $form['#submit'][] = 'drupalform_form_submit';


 /*$submit_handlers = $form_state->getSubmitHandlers();
  $submit_handlers[] = 'drupalform_form_submit';
  $form_state->setSubmitHandlers($submit_handlers);
 */
}

/*function drupalform_system_site_information_phone_submit(array &$form, \Drupal\Core\Form\FormStateInterface $form_state){
  $config = \Drupal::configFactory()->getEditable('system.site');
  $config->set('phone', $form_state->getValue('site_phone'))->save();
}*/


function drupalform_form_submit(array &$form, \Drupal\Core\Form\FormStateInterface $form_state){
  $config = \Drupal::configFactory()->getEditable('system.site');
  $config->set('phonenumber', $form_state->getValue('site_phone'))->save();
}